# ~/.tmuxinator/eds.yml
#
name: dev
root: ~/
startup_window: dev
startup_pane: 1

windows:
  - general:
      layout: even-vertical
      panes:
        - clear; neofetch
        - clear; figlet -w $COLUMNS -kc "General"
  - dev:
      root: ~/git
      layout: even-vertical
      panes:
        - clear; figlet -w $COLUMNS -kc "Dev\\!"
        - 
  - updates:
      panes:
        - brew update; brew outdated
