# ~/.tmuxinator/eds.yml
#
name: dev
root: ~/
startup_window: dev
startup_pane: 1

windows:
  - general:
      panes:
        - clear
  - dev:
      root: ~/git
      layout: even-vertical
      panes:
        - 
        - 
  - updates:
      panes:
        - brew update; brew outdated
